type ArdArtResponseStatus = 'error' | 'bad_request' | 'success' | 'unauthorized' | 'unknown'
// Generated by https://quicktype.io

export interface ArdArtMetalandLogin {
    token: string;
}

export interface ArdArtResponse<T> {
    code: number;
    status: ArdArtResponseStatus;
    message: string;
    result: T;
}

// Generated by https://quicktype.io

export type ArdArtMetalandLoginResponse = ArdArtResponse<{
    jwtToken: string;
    accountId: number;
}>

export type ArdArtBalanceResponse = ArdArtResponse<any[]>


// Generated by https://quicktype.io

export interface ArdArtTicketResponse {
    code: number;
    status: string;
    message: string;
    result: Result;
}

export interface Result {
    count: number;
    records: Record[];
}

export interface Record {
    id: number;
    createdAt: string;
    updatedAt: string;
    isOutOfStock: boolean;
    name: string;
    description: string;
    assetId: number;
    link: string;
    imageUrl: string;
    objectUrl: string;
    category: number;
    price: number;
}


export interface ArdArtInvoiceResult {
    id: number;
    createdAt: string;
    updatedAt: string;
    accountId: number;
    toAccountId: null;
    amount: number;
    isTicket: null;
    prevAmount: number;
    tan: string;
    qrCode: null;
    desc: string;
    successResponse: null;
    errorResponse: null;
    type: string;
    swapType: null;
    method: string;
    transactionType: string;
    status: string;
    txInvoiceId: number;
    txHash: string;
    account: null;
    txRef: null;
    qpayInvoiceId: null;
    createdById: number;
    apiKey: string;
    webhook: null;
}

// Generated by https://quicktype.io

export interface ArdArtUpdateInvoiceQPayResult {
    id: number;
    response: {
        qr_image: string;
        invoice_id: string;
        qr_text: string;
        urls: {
            name: string;
            description: string;
            link: string;
        }[];
        qPay_shortUrl: string;
    };
}

// Generated by https://quicktype.io

export interface ArdArtUpdateInvoiceSocialPayResult {
    id: number;
    response: Response;
}

export interface Response {
    checksum: string;
    transactionId: string;
    invoice: string;
}
