// Generated by https://quicktype.io

export type MonXanshCurrency = 'USD|MNT' | 'RUB|MNT'

export interface MonXanshRateResponse {
    last_date: string;
    code: string;
    rate: string;
    rate_float: number;
    name: string;
}
