// Generated by https://quicktype.io

export interface IdaxUserInfoResponse {
    code: string;
    msg: string;
    message: null;
    data: Data;
}

export interface Data {
    id: number;
    isSub: number;
    subUserDepositOpen: number;
    nickName: string;
    countryCode: string;
    mobileNumber: string;
    userAccount: string;
    email: string;
    accountStatus: number;
    googleStatus: number;
    isOpenMobileCheck: number;
    isCapitalPwordSet: number;
    realName: string;
    lastName: string;
    firstName: string;
    sumsubLevelName: string;
    realAuthType: number;
    authLevel: number;
    notPassReason: null;
    authCountryCode: string;
    etfLocalLimit: string;
    agentStatus: number;
    roleName: string;
    exportExcelAuth: string;
    myMarket: any[];
    invitedCode: string;
    inviteCode: string;
    inviteUrl: string;
    inviteQECode: string;
    lastLoginIp: string;
    lastLoginTime: string;
    feeCoin: string;
    feeCoinRate: string;
    useFeeCoinOpen: number;
    fee_coin_open: string;
    otc_save_ad_on_off: number;
    otcCompanyInfo: OtcCompanyInfo;
    userCompanyInfo: UserCompanyInfo;
    useEtf: string;
    hasFiatBank: string;
    openAuditReport: boolean;
}

export interface OtcCompanyInfo {
    marginCoinSymbol: string;
    otcCompanyApplyEmail: string;
    normalTradeLimit: string;
    normalCompanyMarginNum: string;
    status: string;
}

export interface UserCompanyInfo {
    otcCompanyMarginNum: string;
    applyStatus: string;
    status: string;
}
