// Generated by https://quicktype.io

export interface IdaxTickerResponse {
    high: string;
    vol: string;
    last: string;
    low: string;
    buy: number;
    sell: number;
    rose: string;
    time: number;
    open: string;
}
