// Generated by https://quicktype.io

export interface CognitoSignupResponse {
    CodeDeliveryDetails: CognitoCodeDeliveryDetails;
    UserConfirmed:       boolean;
    UserSub:             string;
}

export interface CognitoCodeDeliveryDetails {
    AttributeName:  string;
    DeliveryMedium: string;
    Destination:    string;
}

// Generated by https://quicktype.io

export interface CognitoSignupRequest {
    ClientId:       string;
    Password:       string;
    UserAttributes: UserAttribute[];
    Username:       string;
}

export interface UserAttribute {
    Name:  string;
    Value: string;
}


// Generated by https://quicktype.io

export interface CognitoConfirmSignup {
    ClientId:         string;
    ConfirmationCode: string;
    Username:         string;
}

// Generated by https://quicktype.io

export interface CognitoGetUser {
    AccessToken: string;
}

// Generated by https://quicktype.io

export interface CognitoUser {
    UserAttributes: UserAttribute[];
    Username:       string;
}

export interface UserAttribute {
    Name:  string;
    Value: string;
}

// Generated by https://quicktype.io

export interface CognitoRefreshToken {
    AuthFlow:       string;
    AuthParameters: AuthParameters;
    ClientId:       string;
}

export interface AuthParameters {
    REFRESH_TOKEN: string;
}

// Generated by https://quicktype.io

export interface CognitoRefreshTokenResponse {
    AuthenticationResult: AuthenticationResult;
    ChallengeParameters:  ChallengeParameters;
}

export interface AuthenticationResult {
    AccessToken: string;
    ExpiresIn:   number;
    IdToken:     string;
    TokenType:   string;
}

export interface ChallengeParameters {
}

// Generated by https://quicktype.io

export interface CognitoForgotPassword {
    ClientId: string;
    Username: string;
}
// Generated by https://quicktype.io

export interface CognitoForgotPasswordResponse {
    CodeDeliveryDetails: CodeDeliveryDetails;
}

export interface CodeDeliveryDetails {
    AttributeName:  string;
    DeliveryMedium: string;
    Destination:    string;
}
// Generated by https://quicktype.io

export interface CognitoConfirmForgotPassword {
    ClientId:         string;
    ConfirmationCode: string;
    Password:         string;
    Username:         string;
}
// Generated by https://quicktype.io

export interface CognitoSignupResend {
    ClientId: string;
    Username: string;
}
