/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/LHC.glb ./src/components/models/LHC.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LHC.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.braccio_destro.geometry} material={materials.yellow} position={[0.34, 6.84, 1.1]} rotation={[1.59, 0.04, -0.01]} scale={0.04} />
      <mesh geometry={nodes.braccio_sinistro.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.corpo.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.gamba_destra.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.gamba_sinistra.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.pinza_destra.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.pinza_sinistra.geometry} material={materials.yellow} position={[-2.04, -0.09, -1.84]} rotation={[1.59, 0, 0.04]} scale={0.04} />
      <mesh geometry={nodes.testa.geometry} material={materials.yellow} position={[0.85, 7.57, 0.46]} rotation={[1.71, 0.03, -0.18]} scale={0.04} />
    </group>
  )
}

useGLTF.preload('/LHC.glb')
