/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Galaa_pose_A.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Galaa_pose_A.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01.geometry} material={materials.Hand} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_1.geometry} material={materials.CHEST} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_2.geometry} material={materials.Leg} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_3.geometry} material={materials.Belt1} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_4.geometry} material={materials.Arm} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_5.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_6.geometry} material={materials.blinn6} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_7.geometry} material={materials.phong4} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_8.geometry} material={materials.hair1} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_9.geometry} material={materials.boolt} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_10.geometry} material={materials.galaa1} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_11.geometry} material={materials.teeth1} />
      <mesh geometry={nodes.Galaa_Pose_01_b_posepose_01_12.geometry} material={materials.eyes1} />
    </group>
  )
}

useGLTF.preload('/Galaa_pose_A.glb')
